// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgywxizxtbqgahonzfkk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJneXd4aXp4dGJxZ2Fob256ZmtrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNjExNjksImV4cCI6MjA2NjgzNzE2OX0.eD1GCHHAZCi-QOSDyOcSMcb5bbfwgGtZrEJvc282am0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});